[package]
name = "xxh3"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "xxh3"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
xxhash-rust = { git = "https://github.com/farhadi/xxhash-rust.git", features = ["xxh3"] }
